-- V1: PostGIS extension, schema, and spatial index. No seed data.

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE gas_station (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    osm_id      BIGINT UNIQUE,
    name        VARCHAR(255),
    brand       VARCHAR(255),
    address     VARCHAR(255),
    location    geography(Point, 4326) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE
);

-- GiST spatial index: makes ST_DWithin / nearest-neighbor queries fast.
CREATE INDEX idx_gas_station_location ON gas_station USING GIST (location);

CREATE TABLE price_report (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id   BIGINT NOT NULL REFERENCES gas_station(id),
    fuel_type    VARCHAR(16) NOT NULL,
    price        NUMERIC(6,3) NOT NULL,
    reporter_id  VARCHAR(255),
    reported_at  TIMESTAMP(6) WITH TIME ZONE
);
CREATE INDEX idx_report_station_fuel_time ON price_report (station_id, fuel_type, reported_at);

-- No seed data — stations and price reports are created at runtime via the API/UI.
